---
- name: Install
  sudo: yes
  apt: pkg=git state=latest

- name: Enable colors
  command: git config --global color.ui true
  changed_when: false
  
- name: Download autocomplete
  get_url: 
      url=https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash
      dest=~/.git-completion.bash

- name: Check .bash_profile
  command:
      touch ~/.bash_profile
      creates=~/.bash_profile
      
- name: Check autocomplete registered
  command:
      grep -Fxqsc "if [ -f ~/.git-completion.bash ]; then" ~/.bash_profile
  register: autocomplete_registered
  changed_when: false
  failed_when: false
  
- name: Register autocomplete
  shell:
    echo "if [ -f ~/.git-completion.bash ]; then" >> ~/.bash_profile &&
    echo "  . ~/.git-completion.bash" >> ~/.bash_profile &&
    echo "fi" >> ~/.bash_profile
  when: not autocomplete_registered